# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # top level image is the container everything runs in
      - image: circleci/node
      - image: nlknguyen/alpine-shellcheck:v0.4.6
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mongo
      - image: circleci/redis

    working_directory: ~/repo
    parallelism: 1

    steps:
      - checkout

      - run:
          name: Check Scripts
          command: |
            node -v && npm -v

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Check Scripts
          command: |
            sudo mkdir /var/log/spotifier
            sudo chown -R `whoami` /var/log/*
            yarn add global mocha
        
      # run tests!
      # - run: yarn test
      - run: mkdir ~/junit
      - run:
          command: 
          yarn add global mocha
          mocha tests/run-tests.js --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit